title: 'Theme Settings'
data:
  title: 'Theme Settings'
  color_option_title: 'color option'
  header_type_title: 'Header Type'
  header_type: sticky
  theme_options:
    -
      id: mgt2hak3
      type: new_set
      enabled: true
      name: Green
      value: primary
      css_class: theme-primary
    -
      id: mgt2iwa5
      name: Caramel
      value: purple
      css_class: theme-purple
      type: new_set
      enabled: true
    -
      id: mgt2j5wl
      name: Brown
      value: brown
      css_class: theme-brown
      type: new_set
      enabled: true
    -
      id: mgtaf35n
      name: Blue
      value: blue
      css_class: theme-blue
      type: new_set
      enabled: true
